table_name: country_level_revenue
name: "Country Level Revenue"
input_csv: data/raw/GO_test_5m.csv
output_parquet: data/processed/country_level_revenue.parquet
output_arrow: data/processed/country_level_revenue.arrow
columns:
  - name: country
    type: string
  - name: product_name
    type: string
  - name: total_price
    type: float
    aggregate: sum
  - name: quantity
    type: int
    aggregate: sum
sort_by:
  column: total_price
  order: desc
url_endpoint: /api/country-level-revenue 