table_name: monthly_sales_sum
input_csv: data/raw/GO_test_5m.csv
output_parquet: data/processed/monthly_sales_sum.parquet
output_arrow: data/processed/monthly_sales_sum.arrow
columns:
  - name: transaction_date
    type: string
  - name: total_price
    type: float
    aggregate: sum
sort_by:
  column: total_price
  order: desc
url_endpoint: /api/monthly-sales-sum 